"""Generate web/css/theme-vars.css from app/themes.py's THEMES dict.

Keeps the future web frontend's color palette in sync with the single
source of truth already used by the Tkinter UI, instead of manually
transcribing hex values into CSS by hand — which could silently drift
out of sync the next time someone tweaks THEMES in app/themes.py.

Run whenever THEMES changes:
    python scripts/generate_theme_css.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.themes import THEMES

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "web" / "css" / "theme-vars.css"

# Maps each app/themes.py THEMES key to the CSS custom property name it
# becomes. Keeping this mapping explicit (rather than auto-lowercasing)
# means a typo'd or renamed key in THEMES fails loudly instead of quietly
# producing a differently-named CSS variable.
KEY_TO_CSS_VAR = {
    "BG": "--bg",
    "BG2": "--bg2",
    "BG3": "--bg3",
    "FG": "--fg",
    "FG_DIM": "--fg-dim",
    "GREEN": "--green",
    "YELLOW": "--yellow",
    "RED": "--red",
    "BLUE": "--blue",
    "CYAN": "--cyan",
    "PURPLE": "--purple",
    "PEACH": "--peach",
    "ACCENT": "--accent",
    "ACCENT_HOVER": "--accent-hover",
    "ON_ACCENT": "--on-accent",
}


def render_theme_block(selector: str, theme: dict) -> str:
    """Render one CSS rule block mapping a theme dict to custom properties."""
    lines = [f"{selector} {{"]
    for key, css_var in KEY_TO_CSS_VAR.items():
        lines.append(f"  {css_var}: {theme[key]};")
    lines.append("}")
    return "\n".join(lines)


def generate_css() -> str:
    """Build the full contents of theme-vars.css from THEMES."""
    header = (
        "/* AUTO-GENERATED by scripts/generate_theme_css.py — do not edit by hand.\n"
        "   Source of truth: app/themes.py. Re-run the script after changing it.\n"
        "\n"
        "   Usage: set data-theme=\"dark\" on <html> (or remove it / omit it) to\n"
        "   switch modes — see web/README.md. */\n\n"
    )
    light_block = render_theme_block(":root", THEMES["light"])
    dark_block = render_theme_block('[data-theme="dark"]', THEMES["dark"])
    return header + light_block + "\n\n" + dark_block + "\n"


def main() -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    css = generate_css()
    OUTPUT_PATH.write_text(css, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
